package de.fhma.ss10.srn.tischbein.gui.forms;

// CHECKSTYLE:OFF
public class UploadForm extends javax.swing.JFrame {

    private static final long serialVersionUID = -6128747519959199333L;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton abbortButton;
    protected javax.swing.JTextField filenameField;
    protected javax.swing.JTextField hashField;
    protected javax.swing.JProgressBar hashingProgress;
    protected javax.swing.JButton saveButton;
    protected javax.swing.JButton searchButton;
    protected javax.swing.JTextField secretField;

    // End of variables declaration//GEN-END:variables
    /** Creates new form UploadForm. */
    public UploadForm() {
        this.initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel jPanel4 = new javax.swing.JPanel();
        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        this.filenameField = new javax.swing.JTextField();
        this.searchButton = new javax.swing.JButton();
        javax.swing.JSeparator jSeparator2 = new javax.swing.JSeparator();
        javax.swing.JPanel jPanel2 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        this.hashField = new javax.swing.JTextField();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        this.secretField = new javax.swing.JTextField();
        javax.swing.JSeparator jSeparator1 = new javax.swing.JSeparator();
        javax.swing.JPanel jPanel3 = new javax.swing.JPanel();
        this.hashingProgress = new javax.swing.JProgressBar();
        this.saveButton = new javax.swing.JButton();
        this.abbortButton = new javax.swing.JButton();

        this.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        this.setTitle("Datei hochladen...");
        this.setAlwaysOnTop(true);
        this.setResizable(false);

        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));
        jPanel1.add(this.filenameField);

        this.searchButton.setText("Durchsuchen...");
        jPanel1.add(this.searchButton);

        jPanel4.add(jPanel1);
        jPanel4.add(jSeparator2);

        jPanel2.setLayout(new java.awt.GridLayout(2, 2, 5, 5));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Datei-Hash:");
        jPanel2.add(jLabel1);

        this.hashField.setEditable(false);
        jPanel2.add(this.hashField);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Datei-Schlüssel:");
        jPanel2.add(jLabel2);

        this.secretField.setEditable(false);
        jPanel2.add(this.secretField);

        jPanel4.add(jPanel2);
        jPanel4.add(jSeparator1);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));
        jPanel3.add(this.hashingProgress);

        this.saveButton.setText("Speichern");
        jPanel3.add(this.saveButton);

        this.abbortButton.setText("Abbrechen");
        jPanel3.add(this.abbortButton);

        jPanel4.add(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this.getContentPane());
        this.getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
                jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
                jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                javax.swing.GroupLayout.PREFERRED_SIZE));

        this.pack();
    }// </editor-fold>//GEN-END:initComponents

}
//CHECKSTYLE:ON
