package de.fhma.ss10.srn.tischbein.gui.forms;

import javax.swing.DefaultListModel;
import javax.swing.JList;

// CHECKSTYLE:OFF

public class WorkForm extends javax.swing.JFrame {

    private static final long serialVersionUID = 5702577045631188956L;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton closeButton;
    protected javax.swing.JButton deleteButton;
    protected javax.swing.JTextArea fileView;
    protected javax.swing.JButton logoutButton;
    protected javax.swing.JList myFilesList;
    protected javax.swing.JList otherFilesList;
    protected javax.swing.JButton uploadButton;
    protected javax.swing.JList userList;

    // End of variables declaration//GEN-END:variables

    /** Creates new form WorkForm */
    public WorkForm() {
    	// TEST !!!!!
        this.initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel buttonPanel = new javax.swing.JPanel();
        this.logoutButton = new javax.swing.JButton();
        this.closeButton = new javax.swing.JButton();
        javax.swing.JPanel titlePanel = new javax.swing.JPanel();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        javax.swing.JSplitPane jSplitPane1 = new javax.swing.JSplitPane();
        javax.swing.JPanel filesPanel = new javax.swing.JPanel();
        javax.swing.JPanel myFilesPanel = new javax.swing.JPanel();
        javax.swing.JScrollPane jScrollPane2 = new javax.swing.JScrollPane();
        this.myFilesList = new javax.swing.JList();
        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
 
        this.uploadButton = new javax.swing.JButton();
        this.deleteButton = new javax.swing.JButton();
        
        javax.swing.JPanel otherFilesPanel = new javax.swing.JPanel();
        javax.swing.JScrollPane jScrollPane3 = new javax.swing.JScrollPane();     
        this.otherFilesList = new javax.swing.JList();
        
        javax.swing.JSplitPane jSplitPane2 = new javax.swing.JSplitPane();
        javax.swing.JPanel viewPanel = new javax.swing.JPanel();
        javax.swing.JScrollPane jScrollPane4 = new javax.swing.JScrollPane();
        
        this.fileView = new javax.swing.JTextArea();
        javax.swing.JPanel userPanel = new javax.swing.JPanel();
        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        this.userList = new javax.swing.JList();

        this.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        this.setTitle("Tischbein v0.1");
        this.setMinimumSize(new java.awt.Dimension(640, 480));

        buttonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        this.logoutButton.setText("Logout");
        buttonPanel.add(this.logoutButton);

        this.closeButton.setText("Beenden");
        buttonPanel.add(this.closeButton);

        this.getContentPane().add(buttonPanel, java.awt.BorderLayout.SOUTH);

        jLabel1.setFont(new java.awt.Font("Candara", 1, 18));
        jLabel1.setText("Tischbein v0.1");
        titlePanel.add(jLabel1);

        this.getContentPane().add(titlePanel, java.awt.BorderLayout.NORTH);

        jSplitPane1.setContinuousLayout(true);

        filesPanel.setMinimumSize(new java.awt.Dimension(150, 130));
        filesPanel.setPreferredSize(new java.awt.Dimension(150, 478));
        filesPanel.setLayout(new javax.swing.BoxLayout(filesPanel, javax.swing.BoxLayout.PAGE_AXIS));

        myFilesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Eigene Dateien"));
        myFilesPanel.setLayout(new javax.swing.BoxLayout(myFilesPanel, javax.swing.BoxLayout.LINE_AXIS));

        jScrollPane2.setViewportView(this.myFilesList);

        myFilesPanel.add(jScrollPane2);

        filesPanel.add(myFilesPanel);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        this.uploadButton.setText("Hochladen");
        jPanel1.add(this.uploadButton);

        this.deleteButton.setText("Löschen");
        jPanel1.add(this.deleteButton);

        filesPanel.add(jPanel1);

        otherFilesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Freigeschaltete Dateien"));
        otherFilesPanel.setLayout(new javax.swing.BoxLayout(otherFilesPanel, javax.swing.BoxLayout.LINE_AXIS));

        jScrollPane3.setViewportView(this.otherFilesList);

        otherFilesPanel.add(jScrollPane3);

        filesPanel.add(otherFilesPanel);

        jSplitPane1.setLeftComponent(filesPanel);

        jSplitPane2.setResizeWeight(1.0);
        jSplitPane2.setContinuousLayout(true);

        viewPanel.setLayout(new javax.swing.BoxLayout(viewPanel, javax.swing.BoxLayout.LINE_AXIS));

        this.fileView.setColumns(20);
        this.fileView.setRows(5);
        jScrollPane4.setViewportView(this.fileView);

        viewPanel.add(jScrollPane4);

        jSplitPane2.setLeftComponent(viewPanel);

        userPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory
                .createTitledBorder("Benutzererlaubnis")));
        userPanel.setMinimumSize(new java.awt.Dimension(150, 63));
        userPanel.setPreferredSize(new java.awt.Dimension(150, 130));
        userPanel.setLayout(new javax.swing.BoxLayout(userPanel, javax.swing.BoxLayout.LINE_AXIS));

        this.userList.setMinimumSize(new java.awt.Dimension(80, 100));
        this.userList.setPreferredSize(new java.awt.Dimension(80, 100));
        jScrollPane1.setViewportView(this.userList);

        userPanel.add(jScrollPane1);

        jSplitPane2.setRightComponent(userPanel);

        jSplitPane1.setRightComponent(jSplitPane2);

        this.getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        this.pack();
    }// </editor-fold>//GEN-END:initComponents

}
//CHECKSTYLE:ON
