/*
 * To change this template, choose Tools | Templates and open the template in the editor.
 */

/*
 * UploadForm.java Created on 17.05.2010, 19:23:52
 */

package de.fhma.ss10.srn.tischbein.gui.forms;

// CHECKSTYLE:OFF
public class UploadForm extends javax.swing.JFrame {

    private static final long serialVersionUID = -6128747519959199333L;

    /**
     * @param args
     *            the command line arguments
     */
    public static void main(final String[] args) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UploadForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;

    private javax.swing.JButton jButton2;

    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;

    // End of variables declaration//GEN-END:variables
    /** Creates new form UploadForm. */
    public UploadForm() {
        this.initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        this.jPanel1 = new javax.swing.JPanel();
        this.jTextField1 = new javax.swing.JTextField();
        this.jButton1 = new javax.swing.JButton();
        this.jSeparator2 = new javax.swing.JSeparator();
        this.jPanel2 = new javax.swing.JPanel();
        this.jLabel1 = new javax.swing.JLabel();
        this.jTextField2 = new javax.swing.JTextField();
        this.jLabel2 = new javax.swing.JLabel();
        this.jTextField3 = new javax.swing.JTextField();
        this.jSeparator1 = new javax.swing.JSeparator();
        this.jPanel3 = new javax.swing.JPanel();
        this.jProgressBar1 = new javax.swing.JProgressBar();
        this.jButton2 = new javax.swing.JButton();
        this.jButton3 = new javax.swing.JButton();

        this.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        this.getContentPane().setLayout(new javax.swing.BoxLayout(this.getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        this.jPanel1.setLayout(new javax.swing.BoxLayout(this.jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        this.jTextField1.setText("jTextField1");
        this.jPanel1.add(this.jTextField1);

        this.jButton1.setText("jButton1");
        this.jPanel1.add(this.jButton1);

        this.getContentPane().add(this.jPanel1);
        this.getContentPane().add(this.jSeparator2);

        this.jPanel2.setLayout(new java.awt.GridLayout(2, 2, 5, 5));

        this.jLabel1.setText("jLabel1");
        this.jPanel2.add(this.jLabel1);

        this.jTextField2.setText("jTextField2");
        this.jPanel2.add(this.jTextField2);

        this.jLabel2.setText("jLabel2");
        this.jPanel2.add(this.jLabel2);

        this.jTextField3.setText("jTextField3");
        this.jPanel2.add(this.jTextField3);

        this.getContentPane().add(this.jPanel2);
        this.getContentPane().add(this.jSeparator1);

        this.jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));
        this.jPanel3.add(this.jProgressBar1);

        this.jButton2.setText("jButton2");
        this.jPanel3.add(this.jButton2);

        this.jButton3.setText("jButton3");
        this.jPanel3.add(this.jButton3);

        this.getContentPane().add(this.jPanel3);

        this.pack();
    }// </editor-fold>//GEN-END:initComponents

}
//CHECKSTYLE:ON
