package de.fhma.ss10.srn.tischbein.gui.forms;

// CHECKSTYLE:OFF

public class WorkForm extends javax.swing.JFrame {

    private static final long serialVersionUID = 5702577045631188956L;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton closeButton;
    protected javax.swing.JButton deleteButton;
    protected javax.swing.JTextArea fileView;
    private javax.swing.JSeparator jSeparator1;
    protected javax.swing.JButton logoutButton;
    protected javax.swing.JList myFilesLlist;
    protected javax.swing.JList otherFilesList;
    protected javax.swing.JButton uploadButton;
    protected javax.swing.JTable userTable;
    // End of variables declaration//GEN-END:variables

    /** Creates new form WorkForm */
    public WorkForm() {
        this.initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel buttonPanel = new javax.swing.JPanel();
        logoutButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        javax.swing.JPanel titlePanel = new javax.swing.JPanel();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        javax.swing.JSplitPane jSplitPane1 = new javax.swing.JSplitPane();
        javax.swing.JPanel filesPanel = new javax.swing.JPanel();
        javax.swing.JPanel myFilesPanel = new javax.swing.JPanel();
        javax.swing.JScrollPane jScrollPane2 = new javax.swing.JScrollPane();
        myFilesLlist = new javax.swing.JList();
        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        uploadButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        javax.swing.JPanel otherFilesPanel = new javax.swing.JPanel();
        javax.swing.JScrollPane jScrollPane3 = new javax.swing.JScrollPane();
        otherFilesList = new javax.swing.JList();
        javax.swing.JSplitPane jSplitPane2 = new javax.swing.JSplitPane();
        javax.swing.JPanel viewPanel = new javax.swing.JPanel();
        javax.swing.JScrollPane jScrollPane4 = new javax.swing.JScrollPane();
        fileView = new javax.swing.JTextArea();
        javax.swing.JPanel userPanel = new javax.swing.JPanel();
        javax.swing.JScrollPane jScrollPane5 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tischbein v0.2");
        setMinimumSize(new java.awt.Dimension(640, 480));

        buttonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        logoutButton.setText("Logout");
        buttonPanel.add(logoutButton);

        closeButton.setText("Beenden");
        buttonPanel.add(closeButton);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.SOUTH);

        jLabel1.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel1.setText("Tischbein v0.2 Ultra Deluxe Gourmet Version");
        titlePanel.add(jLabel1);

        getContentPane().add(titlePanel, java.awt.BorderLayout.NORTH);

        jSplitPane1.setContinuousLayout(true);

        filesPanel.setMinimumSize(new java.awt.Dimension(150, 130));
        filesPanel.setPreferredSize(new java.awt.Dimension(150, 478));
        filesPanel.setLayout(new javax.swing.BoxLayout(filesPanel, javax.swing.BoxLayout.PAGE_AXIS));

        myFilesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Eigene Dateien"));
        myFilesPanel.setLayout(new javax.swing.BoxLayout(myFilesPanel, javax.swing.BoxLayout.LINE_AXIS));

        jScrollPane2.setViewportView(myFilesLlist);

        myFilesPanel.add(jScrollPane2);

        filesPanel.add(myFilesPanel);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        uploadButton.setText("Hochladen");
        jPanel1.add(uploadButton);

        deleteButton.setText("Löschen");
        jPanel1.add(deleteButton);

        filesPanel.add(jPanel1);
        filesPanel.add(jSeparator1);

        otherFilesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Freigeschaltete Dateien"));
        otherFilesPanel.setLayout(new javax.swing.BoxLayout(otherFilesPanel, javax.swing.BoxLayout.LINE_AXIS));

        jScrollPane3.setViewportView(otherFilesList);

        otherFilesPanel.add(jScrollPane3);

        filesPanel.add(otherFilesPanel);

        jSplitPane1.setLeftComponent(filesPanel);

        jSplitPane2.setResizeWeight(1.0);
        jSplitPane2.setContinuousLayout(true);

        viewPanel.setLayout(new javax.swing.BoxLayout(viewPanel, javax.swing.BoxLayout.LINE_AXIS));

        fileView.setColumns(20);
        fileView.setRows(5);
        jScrollPane4.setViewportView(fileView);

        viewPanel.add(jScrollPane4);

        jSplitPane2.setLeftComponent(viewPanel);

        userPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Benutzererlaubnis")));
        userPanel.setMinimumSize(new java.awt.Dimension(150, 63));
        userPanel.setPreferredSize(new java.awt.Dimension(150, 130));
        userPanel.setLayout(new javax.swing.BoxLayout(userPanel, javax.swing.BoxLayout.LINE_AXIS));

        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(userTable);

        userPanel.add(jScrollPane5);

        jSplitPane2.setRightComponent(userPanel);

        jSplitPane1.setRightComponent(jSplitPane2);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

}
//CHECKSTYLE:ON
