/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * WorkForm.java
 *
 * Created on 15.05.2010, 16:48:44
 */

package de.fhma.ss10.srn.tischbein.gui.forms;

/**
 *
 * @author smolli
 */
public class WorkForm extends javax.swing.JFrame {

    /** Creates new form WorkForm */
    public WorkForm() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        buttonPanel = new javax.swing.JPanel();
        logoutButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        titlePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tischbein v0.1");
        setMinimumSize(new java.awt.Dimension(640, 480));

        listPanel.setLayout(new javax.swing.BoxLayout(listPanel, javax.swing.BoxLayout.LINE_AXIS));

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        listPanel.add(jScrollPane1);

        getContentPane().add(listPanel, java.awt.BorderLayout.EAST);

        logoutButton.setText("Logout");
        buttonPanel.add(logoutButton);

        closeButton.setText("Beenden");
        buttonPanel.add(closeButton);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.SOUTH);

        jLabel1.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel1.setText("Tischbein v0.1");
        titlePanel.add(jLabel1);

        getContentPane().add(titlePanel, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WorkForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    protected javax.swing.JButton closeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel listPanel;
    protected javax.swing.JButton logoutButton;
    private javax.swing.JPanel titlePanel;
    // End of variables declaration//GEN-END:variables

}
